name: mobileCameras
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - numpy=1.21.1
  - pandas=1.3.4
  - matplotlib=3.5.0
  - py4j=0.10.9.2
  - pyyaml=6.0
  - pygmo=2.18.0
  - jupyterlab=3.2.1
  - scipy=1.7.1
