version: "1.0"
repast_jar_path: "../simulator/runnable_jar/mobileCameras_91cb5f6.jar"
repast_rs: "../simulator/mobileCameras_main.rs/"
repast_wia_rs: "../simulator/mobileCameras_wia.rs/"
trace_real_path: "../simulator/traces_real/test_random3-D-3333.txt"
init_scenario_path: "../simulator/traces_real/init_random3_10o_10c_2222.xml"
out_scenario_dir: "../../output/${{ time }}/scenario/"
out_trace_dir: "../../output/${{ time }}/trace/"
out_statistics: "../../output/${{ time }}/statistics/"
